### ISSUE TITLE
Implement auto-discovery

### ISSUE THREAD

**Issue by GermanBluefox** [AlCalzone/ioBroker.g-homa#16]

**Comment by AlCalzone** [comment]
Yes, if they are already included in the WiFi network => https://github.com/AlCalzone/node-g-homa

**Comment by GermanBluefox** [comment]
Can you implement auto-discovery? :)

**Comment by AlCalzone** [comment]
I'll try to find the time ;)

**Comment by AlCalzone** [comment]
Fixed by https://github.com/ioBroker/ioBroker.discovery/pull/29
