### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by ldittmar81** [AlCalzone/ioBroker.g-homa#20]
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

**Comment by AlCalzone** [comment]
Fixed by https://github.com/AlCalzone/ioBroker.g-homa/commit/d216b2e071f70a2262a95d53d0771b817d821cd3#diff-8cfead41d88ad47d44509a8ab0a109ad
