### ISSUE TITLE
Version 0.5.1 failed to detect device

### ISSUE THREAD

**Issue by dilmash** [AlCalzone/ioBroker.g-homa#30]
After 0.5.1. installed, the adapter instance did not start e.g. status did not become green. Already installed and detected devices where not found and the the UI did no longer provide information about network adapter to be used, only got adapter Nr. (0)

Downgraded to 0.5.0 solved the problem

**Comment by AlCalzone** [comment]
Are you sure that 0.5.1 was installed correctly?
The only change from 0.5.0 to 0.5.1 was in a file that contains no executable code and merely includes a definition for the connection status object.

**Comment by dilmash** [comment]
Installation was performed by using iobroker admin update function. No problem was reported when installing.

node js; v8.17.0, npm 6.13.4. Problem was immediately solved when installing 0.5.0

**Comment by AlCalzone** [comment]
There are no functional changes from 0.5.0 to 0.5.1 - so the source for the problem must be something else.

**Comment by AlCalzone** [comment]
Is there anything in the ioBroker log?

**Comment by dilmash** [comment]
I re-installed the update and it seems to run without problems now. The UI now looks different as of the last update and the devices are shown.. Fixed for me.  Thanks for a usefull adapter!

**Comment by AlCalzone** [comment]
Alright, closing then
