### ISSUE TITLE
Adapter müllt Log voll

### ISSUE THREAD

**Issue by thatso** [AlCalzone/ioBroker.g-homa#33]
G-Homa Adapter 0.5.1

Alle 30 Minuten werden dieselben bekannten Endgeräte immer wieder neu hinzugefügt.
Der Discovery Adapter läuft **nicht** und die Endgeräte waren die ganze Zeit über im Netz erreichbar.

g-homa.0	2020-05-05 16:52:53.265	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 16:51:10.711	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 16:22:52.964	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 16:21:11.783	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 15:52:52.673	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 15:51:12.764	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 15:22:52.566	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 15:21:13.773	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 14:52:52.491	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 14:51:14.731	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 14:22:52.505	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 14:21:15.566	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 13:52:52.456	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 13:51:16.401	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 13:22:52.362	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 13:21:17.266	info	(4983) Added plug with ID yyyyyy
g-homa.0	2020-05-05 12:52:52.241	info	(4983) Added plug with ID xxxxxx
g-homa.0	2020-05-05 12:51:18.195	info	(4983) Added plug with ID yyyyyy

**Comment by AlCalzone** [comment]
Ist zufällig ein automatischer Neustart oder timer programmiert? Das erscheint mir auffällig regelmäßig.

**Comment by thatso** [comment]
Wie gesagt: alle 30 Minuten. Der Discovery Adapter ist explizit deaktiviert und es sind keine anderen Timer aktiv.

**Comment by AlCalzone** [comment]
Nein ich meine ob bei der Instanz oder so ein schedule definiert ist (expertenansicht). Beim Start einmal loggen welche Geräte gefunden wurden ist ja Ok.

**Comment by thatso** [comment]
Das hatte ich schon so gemeint mit "es sind keine anderen Timer aktiv" - weder bei der G-Homa Instanz noch sonst wo.

**Comment by AlCalzone** [comment]
In ein paar Minuten ist v0.5.2 verfügbar, die hoffentlich alle logs außer dem ersten je Gerät unterdrückt

**Comment by thatso** [comment]
Ich sehe die 0.5.2 im Change Log, wird aber nicht als Update angeboten und ist auch nicht manuell installierbar.

**Comment by AlCalzone** [comment]
Gab nen Fehler beim Releasen. Diesmal sollte es klappen (in ein paar Minuten).

**Comment by AlCalzone** [comment]
Kurzes Feedback obs besser ist wäre super - dann kann ich hier zumachen.

**Comment by thatso** [comment]
Das Problem scheint mit der 0.5.2 erstmal erledigt zu sein.
